"""Initial CivilInfoHub tables

Revision ID: 2ee04824e801
Revises: 
Create Date: 2026-07-18 02:24:35.923713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ee04824e801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categories_category_name_key'), type_='unique')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_user_org_conversation'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_conversation_org'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conversation_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['organisation_id'])

    with op.batch_alter_table('engagement_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_engagement_org'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_engagement_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['organisation_id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('message_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_message_sender'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_org'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_conversation'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['conversation_id'])
        batch_op.drop_column('organisation_id')

    with op.batch_alter_table('monthly_business_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engagement_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('growth_rate', sa.Float(), nullable=True))
        batch_op.alter_column('average_rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('bayesian_rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('trend_score',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_monthly_report'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_monthly_report_org'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['organisation_id'])

    with op.batch_alter_table('organisation_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_org_image_org'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['organisation_id'])

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.alter_column('website_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_org_owner'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_org_location'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_org_category'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['location_id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('ratings_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_user_review'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_review_org'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_review_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['organisation_id'])

    with op.batch_alter_table('review_flags', schema=None) as batch_op:
        batch_op.alter_column('flagged_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_flag_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_flag_review'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ratings_reviews', ['review_id'], ['review_id'])
        batch_op.create_foreign_key(None, 'users', ['flagged_by_user_id'], ['user_id'])
        batch_op.drop_column('flag_status')

    with op.batch_alter_table('saved_organisations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_saved_org'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_saved_org'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_saved_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['organisation_id'])

    with op.batch_alter_table('user_availability', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_availability_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('preference_weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(batch_op.f('unique_user_category_pref'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_pref_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_pref_category'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_user_skill'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_user_skill_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_user_role'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['role_id'])
        batch_op.drop_column('phone')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('volunteer_allocations', schema=None) as batch_op:
        batch_op.alter_column('matching_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_volunteer_allocation'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_allocation_need'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_allocation_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer_needs', ['volunteer_need_id'], ['volunteer_need_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('volunteer_needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('volunteers_needed', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_volunteer_org'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['organisation_id'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('number_of_volunteers_needed')
        batch_op.drop_column('start_date')
        batch_op.drop_column('required_skills')

    with op.batch_alter_table('volunteer_required_skills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_required_skill'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_required_skill_need'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer_needs', ['volunteer_need_id'], ['volunteer_need_id'])

    with op.batch_alter_table('volunteer_signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed_up_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('unique_signup'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_signup_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_signup_need'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer_needs', ['volunteer_need_id'], ['volunteer_need_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('signup_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_signup_need'), 'volunteer_needs', ['volunteer_need_id'], ['volunteer_need_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_signup_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_signup'), ['volunteer_need_id', 'user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('signed_up_at')

    with op.batch_alter_table('volunteer_required_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_required_skill_need'), 'volunteer_needs', ['volunteer_need_id'], ['volunteer_need_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_required_skill'), ['volunteer_need_id', 'skill_name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('volunteer_needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('number_of_volunteers_needed', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_volunteer_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')
        batch_op.drop_column('volunteers_needed')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('needed_date')

    with op.batch_alter_table('volunteer_allocations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_allocation_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_allocation_need'), 'volunteer_needs', ['volunteer_need_id'], ['volunteer_need_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_volunteer_allocation'), ['volunteer_need_id', 'user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('matching_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_role'), 'roles', ['role_id'], ['role_id'], ondelete='RESTRICT')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_skill_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_user_skill'), ['user_id', 'skill_name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pref_category'), 'categories', ['category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_pref_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_user_category_pref'), ['user_id', 'category_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('preference_weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('user_availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_availability_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('saved_organisations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_saved_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_saved_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_saved_org'), ['user_id', 'organisation_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('review_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_flag_review'), 'ratings_reviews', ['review_id'], ['review_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_flag_user'), 'users', ['flagged_by_user_id'], ['user_id'], ondelete='SET NULL')
        batch_op.alter_column('reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('flagged_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ratings_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_review_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_user_review'), ['organisation_id', 'user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_org_category'), 'categories', ['category_id'], ['category_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_org_location'), 'locations', ['location_id'], ['location_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_org_owner'), 'users', ['owner_user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.alter_column('website_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    with op.batch_alter_table('organisation_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_org_image_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')

    with op.batch_alter_table('monthly_business_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_monthly_report_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_monthly_report'), ['organisation_id', 'report_month', 'report_year'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('trend_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=True)
        batch_op.alter_column('bayesian_rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
        batch_op.alter_column('average_rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
        batch_op.drop_column('growth_rate')
        batch_op.drop_column('engagement_score')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_conversation'), 'conversations', ['conversation_id'], ['conversation_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_message_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_message_sender'), 'users', ['sender_user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.alter_column('message_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)

    with op.batch_alter_table('engagement_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_engagement_user'), 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_engagement_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_conversation_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_conversation_org'), 'organisations', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_user_org_conversation'), ['user_id', 'organisation_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('categories_category_name_key'), ['category_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
