"""Initial database tables

Revision ID: 2aefed2162ec
Revises: 
Create Date: 2026-07-25 03:37:02.352651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aefed2162ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('parish', sa.String(length=100), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organisations',
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('organisation_name', sa.String(length=150), nullable=False),
    sa.Column('organisation_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('organisation_id')
    )
    op.create_table('user_availability',
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('available_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('availability_id')
    )
    op.create_table('user_factors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('preference_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_table('user_skills',
    sa.Column('user_skill_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_skill_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('engagement_logs',
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('engagement_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('engagement_id')
    )
    op.create_table('monthly_business_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('report_month', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_saves', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('bayesian_rating', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('trend_status', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('organisation_categories',
    sa.Column('organisation_category_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organisation_category_id'),
    sa.UniqueConstraint('organisation_id', 'category_id', name='unique_organisation_category')
    )
    op.create_table('organisation_factors',
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.PrimaryKeyConstraint('organisation_id')
    )
    op.create_table('organisation_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('ratings_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('saved_organisations',
    sa.Column('saved_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('saved_id')
    )
    op.create_table('volunteer_needs',
    sa.Column('volunteer_need_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('needed_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('urgency_level', sa.String(length=30), nullable=True),
    sa.Column('volunteers_needed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.PrimaryKeyConstraint('volunteer_need_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('encrypted_message_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('review_flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('flagged_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flagged_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['ratings_reviews.review_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_table('volunteer_allocations',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_need_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matching_score', sa.Float(), nullable=True),
    sa.Column('allocation_status', sa.String(length=30), nullable=True),
    sa.Column('allocated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['volunteer_need_id'], ['volunteer_needs.volunteer_need_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('volunteer_required_skills',
    sa.Column('required_skill_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_need_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_need_id'], ['volunteer_needs.volunteer_need_id'], ),
    sa.PrimaryKeyConstraint('required_skill_id')
    )
    op.create_table('volunteer_signups',
    sa.Column('signup_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_need_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['volunteer_need_id'], ['volunteer_needs.volunteer_need_id'], ),
    sa.PrimaryKeyConstraint('signup_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_signups')
    op.drop_table('volunteer_required_skills')
    op.drop_table('volunteer_allocations')
    op.drop_table('review_flags')
    op.drop_table('messages')
    op.drop_table('volunteer_needs')
    op.drop_table('saved_organisations')
    op.drop_table('ratings_reviews')
    op.drop_table('organisation_images')
    op.drop_table('organisation_factors')
    op.drop_table('organisation_categories')
    op.drop_table('monthly_business_reports')
    op.drop_table('engagement_logs')
    op.drop_table('conversations')
    op.drop_table('user_skills')
    op.drop_table('user_preferences')
    op.drop_table('user_factors')
    op.drop_table('user_availability')
    op.drop_table('organisations')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###
