"""Check schema alignment

Revision ID: 686dcf4415df
Revises: f8e8305670c4
Create Date: 2026-07-29 13:56:29.163044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686dcf4415df'
down_revision = 'f8e8305670c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_moderations',
    sa.Column('moderation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('moderation_id')
    )
    with op.batch_alter_table('monthly_business_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_monthly_report'), type_='unique')
        batch_op.drop_index(batch_op.f('unique_monthly_report_idx'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_location'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['location_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_location'), 'locations', ['location_id'], ['location_id'], ondelete='SET NULL')

    with op.batch_alter_table('monthly_business_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_monthly_report_idx'), ['organisation_id', 'report_month', 'report_year'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('unique_monthly_report'), ['organisation_id', 'report_month', 'report_year'], postgresql_nulls_not_distinct=False)

    op.drop_table('user_moderations')
    # ### end Alembic commands ###
