"""add organisation owner names

Revision ID: c74d30c9189f
Revises: 5bd1ed3b7c17
Create Date: 2026-07-28 14:01:37.967769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74d30c9189f'
down_revision = '5bd1ed3b7c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_first_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('owner_last_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_column('owner_last_name')
        batch_op.drop_column('owner_first_name')

    # ### end Alembic commands ###
