"""add organisation owner names

Revision ID: c74d30c9189f
Revises: 5bd1ed3b7c17
Create Date: 2026-07-28 14:01:37.967769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74d30c9189f'
down_revision = '5bd1ed3b7c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_business_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_monthly_report'), type_='unique')
        batch_op.drop_index(batch_op.f('unique_monthly_report_idx'))
        batch_op.drop_column('total_volunteer_signups')

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_first_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('owner_last_name', sa.String(length=80), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_location'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_users_location'), 'locations', ['location_id'], ['location_id'], ondelete='SET NULL')

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_column('owner_last_name')
        batch_op.drop_column('owner_first_name')

    with op.batch_alter_table('monthly_business_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_volunteer_signups', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('unique_monthly_report_idx'), ['organisation_id', 'report_month', 'report_year'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('unique_monthly_report'), ['organisation_id', 'report_month', 'report_year'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
