"""Add recommendation factor tables

Revision ID: f8e8305670c4
Revises: 
Create Date: 2026-07-24 00:28:01.982690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e8305670c4'
down_revision = "c74d30c9189f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_factors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('organisation_factors',
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.PrimaryKeyConstraint('organisation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation_factors')
    op.drop_table('user_factors')
    # ### end Alembic commands ###
